spring.application.name=project
server.port=8080
tour.api.key=${TOUR_API_KEY}
tour.api.key.en=${TOUR_API_KEY_EN}

# MariaDB 연결
spring.datasource.url=jdbc:mariadb://localhost:3306/projectDB?useUnicode=true&characterEncoding=utf8mb4
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# SQL 초기화
spring.sql.init.mode=always

# LocalDate를 "2026-06-08" 형식 문자열로 직렬화
spring.jackson.serialization.write-dates-as-timestamps=false

# MyBatis 설정
mybatis.configuration.map-underscore-to-camel-case=true
